CREATE TABLE IF NOT EXISTS InfoPlayer (
  UserName VARCHAR(50) NOT NULL,
  PassWord VARCHAR(50) NOT NULL,
  Gender   VARCHAR(10) NOT NULL,
  PRIMARY KEY (UserName)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Goal (
  UserName  VARCHAR(50) NOT NULL,
  BestScore INT NOT NULL DEFAULT 0,
  BestLevel INT NOT NULL DEFAULT 1,
  BestTime  VARCHAR(5) NOT NULL DEFAULT '00:00',
  PRIMARY KEY (UserName),
  CONSTRAINT FK_Goal_InfoPlayer FOREIGN KEY (UserName) REFERENCES InfoPlayer(UserName)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS History (
  HistoryID   INT NOT NULL AUTO_INCREMENT,
  UserName    VARCHAR(50) NOT NULL,
  Date        DATE NOT NULL,
  LoginTime   VARCHAR(8) NOT NULL,
  TimesPlayed INT NOT NULL DEFAULT 0,
  Score       INT NOT NULL DEFAULT 0,
  Level       INT NOT NULL DEFAULT 1,
  PlayTime    VARCHAR(5) NOT NULL DEFAULT '00:00',
  PRIMARY KEY (HistoryID),
  CONSTRAINT FK_History_InfoPlayer FOREIGN KEY (UserName) REFERENCES InfoPlayer(UserName)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
